### ISSUE TITLE
Buttons are not keyboard-accessible

### ISSUE THREAD

**Issue by simevidas** [EricHripko/x-material#3]
On http://erichripko.github.io/x-material/, the button demos cannot be reached using the keyboard, i.e. they are not in the TAB sequence.

**Comment by EricHripko** [comment]
Hey Šime,

Well spotted thanks!

**Comment by EricHripko** [comment]
TODO:
- this.tabIndex = 0 for focusable elements
- Check outline styles
- Test in different browsers

**Comment by simevidas** [comment]
More:
- when focused, the Enter and Space keys (either) should activate the button; I think, that will require writing an event handler in JavaScript
- adding the `role="button"` attribute (ARIA) will make screen readers announce it as a button (I didn’t test)

**Comment by EricHripko** [comment]
Hey Šime,

Thanks again! I will make sure to include enter/space interaction. In regards to ARIA, I probably will not be allocating development time to this area just yet - but I will get back to in foreseeable future :)
